cmake_minimum_required(VERSION 3.16)
project(ground_truth_transport_test)
find_package(gz_transport_vendor REQUIRED)
find_package(gz_msgs_vendor REQUIRED)
find_package(gz-transport13 REQUIRED)
find_package(gz-msgs10 REQUIRED)
add_executable(gt_publisher ../ground_truth_transport_smoke.cpp)
target_compile_features(gt_publisher PRIVATE cxx_std_17)
target_link_libraries(gt_publisher gz-transport13::core gz-msgs10::core)
